#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-avahi-dependencies() {
  declare desc="avahi dependencies plugin trigger"
  declare trigger="dependencies"

  if [[ ! -f /etc/apt/sources.list.d/josegonzalez_packages.list ]]; then
    curl -s https://packagecloud.io/install/repositories/josegonzalez/packages/script.deb.sh | sudo bash
  fi

  case "$DOKKU_DISTRO" in
    debian | ubuntu)
      apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --force-yes -qq -y avahi-register
      ;;
  esac
}

trigger-avahi-dependencies "$@"
