#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-avahi-post-stop() {
  declare desc="avahi pre-delete plugin trigger"
  declare trigger="pre-delete"
  declare APP="$1"

  /usr/bin/avahi-register remove --name "$APP"
}

trigger-avahi-post-stop "$@"
